[package]
name = "fsrs"
version = "0.4.1"
authors = ["Open Spaced Repetition"]
categories = ["algorithms", "science"]
edition = "2021"
homepage = "https://github.com/open-spaced-repetition"
keywords = ["spaced-repetition", "algorithm", "fsrs", "machine-learning"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/open-spaced-repetition/fsrs-rs"
rust-version = "1.75.0"
description = "FSRS for Rust, including Optimizer and Scheduler"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.burn]
version = "0.13.0"
# git = "https://github.com/burn-rs/burn.git"
# rev = "d2639682367f39d0d0ed049d0cf3a2077259e05d"
# path = "../burn/burn"
default-features = false
features = ["std", "train", "ndarray"]

[dev-dependencies.burn]
version = "0.13.0"
# git = "https://github.com/burn-rs/burn.git"
# rev = "d2639682367f39d0d0ed049d0cf3a2077259e05d"
# path = "../burn/burn"
default-features = false
features = ["std", "train", "ndarray", "sqlite-bundled"]

[dependencies]
itertools = "0.12.0"
log = "0.4"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
rand = "0.8.5"
rayon = "1.8.0"
serde = "1.0.193"
snafu = "0.8.0"
strum = { version = "0.26.1", features = ["derive"] }

[dev-dependencies]
chrono = { version = "0.4.31", default-features = false, features = ["std", "clock"] }
chrono-tz = "0.8.4"
criterion = { version = "0.5.1" }
rusqlite = { version = "0.30.0" }

[[bench]]
name = "benchmark"
harness = false

[patch.crates-io]
burn = { git = "https://github.com/tracel-ai/burn", rev = "4aa13d6b2528a9c154862e0e7865cd7812e62e94" }
